// import { ProductWithTag } from "@/types/product";

// export const PRODUCTS: ProductWithTag[] = [
//   {
//     id: 1,
//     name: "Royal Banarasi Silk",
//     description: "Pure silk with zari border",
//     price: 12500,
//     imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBtUfaMXHohPhp7MQE1_RZ5LnweWZQ4GxlygxzazeRNXRRbUzNuLKgLx2LDOIDaksS-6dD3XoGxNIpddS47NDz5H2sJNxMt90M4pOanQCWUGjk8gfJE8_o0abRrszht44VlJtYckd3HGRuYjtQkGugoZp-c0BwjqCVgl-54L_h9148RLELfslytFjcwQJjbuI4CdDzFZ-1bw-fPUOc5gmzf0fmB4NuIXznX29751H3SQjIZhN2ionSUTwBR-SIa-hrU8K6-Ou8k_t8",
//     imagePath: "/placeholder/1",
//     category: "Sarees",
//     createdAt: new Date("2024-01-01").toISOString(),
//     tag: "Best Seller",
//     tagColor: "bg-[#D4AF37] text-white",
//   },
//   {
//     id: 2,
//     name: "Floral Organza Lehenga",
//     description: "Hand-painted motifs",
//     price: 18900,
//     imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBsvo2a0ddpk1T63pHYw36h8lXoolS2L8oJbnYwJLltvJp48Wkfo1RVc8574udQYIVAQ4BHgFWP-gUavtNmAezdHxBscJzFZqfOFAvhveCg5yxRvqR1taDaqv32ZUOAJD4Zf78geTtPxFyFQo9J9QhLX3dQC0Zt5y2HwyChn_arWTdLUn4dWKsktdfRdqgNEJOX5KlUOEADoK0avLAT_fdAItGHyzjf9kji48GiGJ2B8oulplwqVpXayMSUYwvcapi4AY7n-L7thOo",
//     imagePath: "/placeholder/2",
//     category: "Lehengas",
//     createdAt: new Date("2024-01-15").toISOString(),
//   },
//   {
//     id: 3,
//     name: "Emerald Chanderi Set",
//     description: "With intricate zari work",
//     price: 70,
//     imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAb3iS8wKxG8aLEbes2HbdfVrYFI_-CPB2EC_9neEjsZPoECIUf0hCi-XSf1c3BR0c3b8csnwKAweV9lWnknLEATUldDLyGzfumzS1xh4rGodqymqbN1TsSlinbQiBNtWWlZjZK5UvtK0LV0xSqIZfZpbFa0tdjB6CB1IryHYNW5H2oOtW5k0UOvVGdWET0AJwLX5OaRxnCf660yYpapowgpYmg67-hUe-Y_ueuDaDedfXnXDSOip6YUJzxYEhEZ08OiKmhmwIoYBk",
//     imagePath: "/placeholder/3",
//     category: "Suits",
//     createdAt: new Date("2024-02-01").toISOString(),
//     tag: "New",
//     tagColor: "bg-[#E8D3D9] text-[#4A403A]",
//   },
//   {
//     id: 4,
//     name: "Ruby Red Kanjivaram",
//     description: "Traditional temple border silk saree",
//     price: 22000,
//     imageUrl: "https://images.unsplash.com/photo-1610189012906-4783382c5780?q=80&w=1000&auto=format&fit=crop",
//     imagePath: "/placeholder/4",
//     category: "Sarees",
//     createdAt: new Date("2024-02-10").toISOString(),
//   },
//   {
//     id: 5,
//     name: "Pastel Anarkali Suit",
//     description: "Georgette flared suit with dupatta",
//     price: 4500,
//     imageUrl: "https://images.unsplash.com/photo-1583391733956-6c78276477e2?q=80&w=1000&auto=format&fit=crop",
//     imagePath: "/placeholder/5",
//     category: "Suits",
//     createdAt: new Date("2024-02-05").toISOString(),
//   },
// ];
